/*限制错误记录数 */
SESSIONS 8;
ERRLIMIT 1; 

LOGON $PARAM{'HOSTNM'}/$PARAM{'USERNM'},$PARAM{'PASSWD'};

/*删除目标表*/
DROP TABLE $PARAM{'TEMP_DB'}.$PARAM{'LOAD_TBL'};

/*删除错误表1*/
DROP TABLE $PARAM{'TEMP_DB'}.$PARAM{'LOAD_ERR_TBL_1'};

/*删除错误表2*/
DROP TABLE $PARAM{'TEMP_DB'}.$PARAM{'LOAD_ERR_TBL_2'};

/*创建目标表*/
CREATE TABLE $PARAM{'TEMP_DB'}.$PARAM{'LOAD_TBL'} AS $PARAM{'TEMP_DB'}.$PARAM{'LOAD_TEMPLATE_TBL'} WITH NO DATA ;

SET RECORD VARTEXT ',' DISPLAY_ERRORS;

DEFINE

ITEM_NBR              (VARCHAR(25))

FILE=$PARAM{'LOAD_DATA_FILE'};

BEGIN LOADING $PARAM{'TEMP_DB'}.$PARAM{'LOAD_TBL'} 
ERRORFILES $PARAM{'TEMP_DB'}.$PARAM{'LOAD_ERR_TBL_1'}, $PARAM{'TEMP_DB'}.$PARAM{'LOAD_ERR_TBL_2'};

INSERT INTO $PARAM{'TEMP_DB'}.$PARAM{'LOAD_TBL'}(
  ITEM_NBR
)
VALUES
(
:ITEM_NBR
);
END LOADING;

LOGOFF;
.QUIT 0;